services:
  # PHP Application
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8080:80'
    environment:
      - DB_HOST=mysql
      - DB_NAME=yii2_basic
      - DB_USER=yii2user
      - DB_PASSWORD=yii2password
    depends_on:
      - mysql

  # MySQL Database
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=yii2_basic
      - MYSQL_USER=yii2user
      - MYSQL_PASSWORD=yii2password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - '8081:80'
    depends_on:
      - mysql

volumes:
  mysql_data:
